spring: 
    application: 
        name: springcloudconfig
    cloud:
        config: 
            server:
                git:
                    uri: https://github.com/Rishav-Madnavat/springCloud.git
                    searchPaths: envRepo
                    # basedir: envRepo
                    default-label: envRepo

server:
    port: 8888
