spring:
    application:
        name: servicei
#     cloud:
#         bootstrap:
#             enabled: true
#         config:
#             uri: http://localhost:8888
#             fail-fast: true

# server:
#     port: 8082
    
# logging:
#     level:  
#         org:
#             springframework:
#                 cloud:  
#                     config: TRACE
#                 boot:
#                     context: 
#                         config: DEBUG

# spring:
    config:
        import: "configserver:http://localhost:8888"
        fail-fast: true
# server:
#     port: 8082


